env : "prod"
storage_path : "./storage.db"
http_server:
  address: "0.0.0.0:8082"
  timeout: 4s # время на чтение запроса и такое же время на ответ
  idle_timeout: 30s # время жизни соединения с клиентом
  user: "USER"